### ISSUE TITLE
Find out the number of seeders and leechers for given torrent ?

### ISSUE THREAD

**Issue by snimavat** [mpetazzoni/ttorrent#188]
Is there an API which i can use to findout the number of seeders/leechers for given torrent file ?

**Comment by mpetazzoni** [comment]
This information is usually collected, and reported, by the tracker, since it has visibility into the peer swarm and what they are doing (and their piece availability).

You can also get that information by having a client start exchanging on that torrent file, but you'll only get partial visibility into a subset of the peer swarm and they seeder/leecher status.
